### ISSUE TITLE
No Time Entries are retrieved

### ISSUE THREAD

**Issue by jarrodmast** [campai-bv/autotask-dashboards-os#40] opened 2013-12-12 00:47 UTC
Refer to my comments in issue #2 
This is still an ongoing problem - we have 0 hours worked and 0 hours billable being reported by all my resources.
I have one specific tech who rarely works in AT, but whatever time he adds always seems to come through. 
This seems like a definite bug - as to who is at fault - the dash code or the AT API - I don't know! let me know how I can be of assistance in getting to the root of this issue.

**Comment by coencoppens** [comment] 2013-12-16 14:38
There are also people reporting they get **some** time entries, just not all of them. I have a feeling it's a time zone thing (yet again).

Because we do get all entries (at least, we think), I'm gonna start debugging by testing our own Dashboards and pretending it's located all over the world.

**Comment by coencoppens** [comment] 2014-01-08 14:11
@jarrodmast so I figured out a way to verify the data gathered by the Dashboard. In Autotask, go to:
Reports > New LiveReports Designer > System Reports > Resource Productivity > Resource Productivity
Run the report with a filter on **Worked Date** set to **today**.

This will give you a report on all worked time today. This should match all the entries in the time_entries table.

Can you check if it matches in your environment?

Edit: See the commit below. Run the cronjob with -d time_entries to only focus on the time entry data.

**Comment by Mayfieldtechnologies** [comment] 2014-02-20 18:09
I am running into the same issue in my environment, and running the report you indicated does show that there is time worked for today.  However, in the cronjob log, I get:

2014-02-20 12:06:17 Cronjob: > Processing the tickets data into totals for all dashboards..
No time entries found with Worked Date = 2014-02-20.

Edit: FWIW, I'm located in the US, and the general standard for dates is m-d-Y.  I tried adjusting the CalculateTotalsForTimeEntriesTask.php to change all of the Y-m-d to m-d-Y, but still got the above error of no time entries.  Kinda figured it wouldn't work, but was worth a shot.

Edit 2:  Trying to dig deeper into this, and confirmed that $oResult is not returning anything in the function __importTimeEntries()

```
$oResult = $this->Timeentry->findInAutotask('all', array(
                                      'conditions' => array(
                                                      'IsThisDay' => array(
                                                                      'DateWorked' => date('Y-m-d')
                                                      )
                                      )
                      ));

                      file_put_contents('/var/www/app/tmp/logs/timedump.log', print_r($oResult,true));
```

/var/www/app/tmp/logs/timedump.log Contents: 

```
Array
(
)
```

**Comment by Mayfieldtechnologies** [comment] 2014-02-21 17:03
I believe I found the solution (at least for my environment).  It was not related to anything in the code, but the account we had linked to the API was set to Service Desk user.  As soon as I set that account to System Administrator, all time entries came through.

**Comment by coencoppens** [comment] 2014-02-24 08:22
@Mayfieldtechnologies wow, that's a pretty huge discovery :-) This might be the cause for people to miss data in several areas!

@jarrodmast , can you check if this solves your issues too?

**Comment by jarrodmast** [comment] 2014-02-24 14:16
Just checked and can confirm this does seem to be my issue!
Changed to administrator and instant data!

**Comment by coencoppens** [comment] 2014-02-24 20:42
Sweet :-) Thanks a lot guys, closing this one up!

**Closed as completed by coencoppens** 2014-02-24 20:42 UTC
Labels: FAQ
